#!/usr/bin/env python3
"""
Sync documentation from Sentinel repos into the sentinel-website docs mirror.

Fetches READMEs, docs/ directories, and extra files from Sentinel-Command,
Sentinel-CameraNode, and Sentinel-HomeAssistant via the GitHub API.
Writes them into docs/documentation/ and generates _sidebar.md.
"""
import subprocess, json, base64, shutil
from pathlib import Path
from datetime import datetime, timezone

ROOT = Path(__file__).parent
MIRROR = ROOT / "docs" / "documentation"

REPOS = [
    {
        "slug": "command",
        "name": "Command Center",
        "github": "Sentinel-Command",
        "files": ["README.md", "AGENTS.md", "CONTRIBUTING.md", "SECURITY.md", "CODE_OF_CONDUCT.md"],
        "dirs": ["docs"],
    },
    {
        "slug": "camera-node",
        "name": "Camera Node",
        "github": "Sentinel-CameraNode",
        "files": ["README.md"],
        "dirs": ["docs"],
    },
    {
        "slug": "home-assistant",
        "name": "Home Assistant",
        "github": "Sentinel-HomeAssistant",
        "files": ["README.md"],
        "dirs": [],
    },
]


def gh_api(path):
    result = subprocess.run(["gh", "api", "--paginate", path], capture_output=True, text=True, timeout=30)
    try:
        return json.loads(result.stdout)
    except (json.JSONDecodeError, ValueError):
        return None


def download_file(repo, filepath, outpath):
    data = gh_api(f"repos/SourceBox-LLC/{repo}/contents/{filepath}")
    if not data or data.get("type") != "file":
        return False
    content = base64.b64decode(data["content"])
    outpath.parent.mkdir(parents=True, exist_ok=True)
    outpath.write_bytes(content)
    return True


def download_dir(repo, dirpath, outdir):
    contents = gh_api(f"repos/SourceBox-LLC/{repo}/contents/{dirpath}")
    if not isinstance(contents, list):
        return 0
    count = 0
    for item in contents:
        if item["type"] == "file" and item["name"].endswith(".md"):
            if download_file(repo, item["path"], outdir / item["name"]):
                count += 1
        elif item["type"] == "dir":
            count += download_dir(repo, item["path"], outdir / item["name"])
    return count


def make_title(filename):
    name = filename.replace(".md", "").replace("_", " ").replace("-", " ")
    replacements = {
        "README": "Overview",
        "AGENTS": "Agent Guide",
        "CONTRIBUTING": "Contributing",
        "SECURITY": "Security Policy",
        "CODE OF CONDUCT": "Code of Conduct",
        "CHANGELOG": "Changelog",
        "BUILD": "Build Guide",
        "LAUNCH HANDOFF": "Launch Handoff",
        "DISASTER RECOVERY": "Disaster Recovery",
        "ON CALL": "On-Call Guide",
        "DPA": "Data Processing Agreement",
        "SUB PROCESSORS": "Sub-Processors",
    }
    for old, new in replacements.items():
        name = name.replace(old, new)
    words = name.split()
    result = []
    for w in words:
        if len(w) <= 3 and w.isupper():
            result.append(w)
        else:
            result.append(w.capitalize())
    return " ".join(result)


def collect_pages(repo_dir):
    pages = []
    if not repo_dir.exists():
        return pages
    for md in sorted(repo_dir.rglob("*.md")):
        rel = md.relative_to(repo_dir)
        if str(rel) == "README.md":
            pages.append(("README", make_title("README")))
        else:
            link = str(rel).replace(".md", "")
            title = make_title(md.stem)
            pages.append((link, title))
    return pages


# ── Main ──
print(f"Sentinel docs sync — {datetime.now(timezone.utc).isoformat()}")

# Preserve index.html, wipe everything else in the mirror dir
if MIRROR.exists():
    for item in MIRROR.iterdir():
        if item.name != "index.html":
            if item.is_dir():
                shutil.rmtree(item)
            else:
                item.unlink()
else:
    MIRROR.mkdir(parents=True)

sidebar_lines = [
    "<!-- Auto-generated by sync_docs.py — do not edit manually -->",
    "",
    "- [Home](README)",
    "",
]

total_files = 0

for repo in REPOS:
    slug = repo["slug"]
    print(f"\n=== {repo['name']} ===")
    repo_dir = MIRROR / slug
    repo_dir.mkdir(parents=True, exist_ok=True)

    for f in repo["files"]:
        if download_file(repo["github"], f, repo_dir / f):
            print(f"  + {f}")
            total_files += 1

    for d in repo["dirs"]:
        count = download_dir(repo["github"], d, repo_dir / d)
        if count:
            print(f"  + {d}/ ({count} files)")
            total_files += count

    pages = collect_pages(repo_dir)
    sidebar_lines.append(f"- **{repo['name']}**")
    has_readme = any(p[0] == "README" for p in pages)
    if has_readme:
        sidebar_lines.append(f"  - [Overview]({slug}/README)")
    for link, title in pages:
        if link == "README":
            continue
        sidebar_lines.append(f"  - [{title}]({slug}/{link})")
    sidebar_lines.append("")

sidebar_lines.append("- [Report a Bug](https://github.com/SourceBox-LLC/Sentinel-Command/issues)")
sidebar_lines.append("- [Edit on GitHub](https://github.com/SourceBox-LLC/sentinel-website)")
sidebar_lines.append("")

(MIRROR / "_sidebar.md").write_text("\n".join(sidebar_lines))
print(f"\nGenerated _sidebar.md ({len(sidebar_lines)} lines)")
print(f"Total docs synced: {total_files} markdown files")
print("Sync complete!")